# config.yml
detection-enabled: true

region:
  start:
    ==: org.bukkit.Location
    world: world
    x: 0
    y: 0
    z: 0
    pitch: 0.0
    yaw: 0.0
  end:
    ==: org.bukkit.Location
    world: world
    x: 0
    y: 0
    z: 0
    pitch: 0.0
    yaw: 0.0
